### ISSUE TITLE
Creative Cloud Files Support?

### ISSUE THREAD

**Issue by JacobDB** [andif888/wenpcfg#1]
Would it be possible to add support for Creative Cloud Files? Stupid thing shows up if you install any Adobe Creative Cloud software and drives me crazy.

**Comment by andif888** [comment]
I have looked through some suggestion on manually removing the link in Windows Explorer.
https://www.reddit.com/r/techsupport/comments/3f4hl2/remove_creative_cloud_files_from_file_explorer/
https://forums.adobe.com/message/7809622#7809622
http://dirkmertens.de/2015/08/08/windows-10-adobe-creative-cloud-files-link-entfernen/

It seems that the guid of the registry key, which has to be modified, is not the same for everybody or constantly changes. That makes it difficult to identify the correct registry key on different systems.
