### ISSUE TITLE
wenpcfg.exe instantly closes when opening

### ISSUE THREAD

**Issue by EtzBetz** [andif888/wenpcfg#3]
Hey there.

I would really like to use your tool, but unfortunately it instantly closes when I want to open it, even with Admin Rights. Is there any way I could help you with a log or so?

**Comment by andif888** [comment]
are you running the tool from a command prompt?

**Comment by mailinglists35** [comment]
this is happening for me on windows 10 anniversary update edition (Version	10.0.14393 Build 14393) 64bit
running by double clicking in file explorer

**Comment by mailinglists35** [comment]
oh, nevermind, the app MUST be run in command prompt, as it is a command line-only utility! :)
