### ISSUE TITLE
Deployment possible?

### ISSUE THREAD

**Issue by Eulender** [andif888/wenpcfg#4]
Hello, 
this tool is fantastic, but i would like to deploy it automaticaly to some clients or run it from an autoit script.
Is this possible? Is there any silent mode? 

tia
Christoph Eder

**Comment by andif888** [comment]
It's a command line tool so i should be silent by default. Or did i misunderstood something?

**Comment by Eulender** [comment]
I have tried it to run in a winsods service as systemuser. No function. I thing the problem are the messages or this many open console windows wen i start the programm as batchjob or from the commandline (as privileged user).

**Comment by Eulender** [comment]
I have tried it to run in a winsods service as systemuser. No function. I thing the problem are the messages or this many open console windows wen i start the programm as batchjob or from the commandline (as privileged user).

**Comment by andif888** [comment]
usually i run it in a GPO startup script.
